#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
echo "--- :docker: :house_with_garden: Running pre-command hook"
./.buildkite/test-hooks/pre-command
echo "--- :docker: Running ./node_libraries/hash_checker create-corejs player-auth player-graphdb pubsub-synchronizer redis-discovery redis-distributed-chunker in BUILDKITE_PLUGIN_SMART_CI_IMAGE"
sh -c ./node_libraries/hash_checker create-corejs player-auth player-graphdb pubsub-synchronizer redis-discovery redis-distributed-chunker
echo "--- :docker: :house_with_garden: Running post-command hook"
./.buildkite/test-hooks/post-command
